name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:

    strategy:
      matrix:
        os: [ { os: windows-latest, runtime: win-x64 }, { os: ubuntu-latest, runtime: linux-x64 } ]

    runs-on: ${{ matrix.os.os }}
    
    name: Publish on ${{ matrix.os.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish ${{ matrix.os.runtime }}
      run: dotnet publish Src/RandomizerTMF -c Release -f net7.0 -r ${{ matrix.os.runtime }} -o RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }} --self-contained
      
    - name: Zip to RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }}.zip
      uses: thedoctor0/zip-release@main
      with:
        path: RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }}
        filename: RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }}.zip
    
    - name: SHA256 checksum
      uses: Huy-Ngo/gha-sha@v1.1.0
      with:
        glob: RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }}.zip
    
    - name: Upload RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }}.zip to latest release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RandomizerTMF.${{ github.ref_name }}.${{ matrix.os.runtime }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: |
          ${{ github.event.release.body }}
          
          The ZIP was automatically generated using the [publish workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
