# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish (temporary)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish win-x64
      run: dotnet publish -c Release -f net7.0 -r win-x64 -o RandomizerTMF.win-x64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:PublishReadyToRun=true --self-contained
    - name: Publish linux-x64
      run: dotnet publish -c Release -f net7.0 -r linux-x64 -o RandomizerTMF.linux-x64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:PublishReadyToRun=true --self-contained
    - name: Upload win-x64 Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: RandomizerTMF.win-x64
        path: RandomizerTMF.win-x64
        retention-days: 7
    - name: Upload linux-x64 Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: RandomizerTMF.linux-x64
        path: RandomizerTMF.linux-x64
        retention-days: 7
