# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish (temporary)

on:
  workflow_dispatch:

jobs:
  build:
  
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        runtime: [ win-x64, linux-x64 ]

    runs-on: ${{ matrix.os }}
    
    name: Publish on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish ${{ matrix.runtime }}
      run: dotnet publish RandomizerTMF -c Release -f net7.0 -r ${{ matrix.runtime }} -o RandomizerTMF.${{ matrix.runtime }} --self-contained
    - name: Upload ${{ matrix.runtime }} Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: RandomizerTMF.${{ matrix.runtime }}
        path: RandomizerTMF.${{ matrix.runtime }}
        retention-days: 7
